login:
  path:              /login
  methods:            GET
  defaults:             { _controller: IMAGLdapBundle:Default:login }

login_check:
  path:              /login_check

logout:
  path:              /logout
